### ISSUE TITLE
unable to find libOpenCvNative.so when setting up/installing EasyOpenCV

### ISSUE THREAD

**Issue by robovines6955** [OpenFTC/EasyOpenCV#29]
Following the link in the install instructions leads to a 404, and the file is not in the opencv repo

**Comment by Windwoes** [comment]
Sorry, yeah, this is because I'm in the process of getting EOCV v1.5.0 released and it will require a new native lib file since I've upgraded the OpenCV core to v4.5.3.

Here's a link to the file (from repo history): https://github.com/OpenFTC/OpenCV-Repackaged/raw/566ee38f413609a95818f9fe566f4d90caf55e0e/doc/libOpenCvNative.so

**Comment by robovines6955** [comment]
Sweet!! We were banging our heads pretty good trying to figure out what we were missing and figured we would just open an issue. Glad we weren't just missing it. Thanks!

**Comment by Windwoes** [comment]
FYI, v1.5.0 has been released

**Comment by robovines6955** [comment]
Thanks mate, we will look at using the new version!
________________________________
