### ISSUE TITLE
startStreaming() does not send frames to processFrame() after a call to stopStreaming()

### ISSUE THREAD

**Issue by ftc14140** [OpenFTC/EasyOpenCV#65]
After a call to stopStreaming(), a subsequent call to startStreaming() on the same webcam does not result in further frames being sent to the attached pipeline.  Logs are attached for the events after the initial call to start, the call to stop, and the subsequent call to (re)start.

[start.txt](https://github.com/OpenFTC/EasyOpenCV/files/10816864/start.txt)
[stop.txt](https://github.com/OpenFTC/EasyOpenCV/files/10816865/stop.txt)
[restart.txt](https://github.com/OpenFTC/EasyOpenCV/files/10816866/restart.txt)

**Comment by Windwoes** [comment]
Wow, how has this bug not been found before now? It's specific to webcams, and usually I just test with the internal camera so I guess that's how I didn't notice it, but surprised nobody else has.

Fixed in https://github.com/OpenFTC/EasyOpenCV/commit/4d050a5cb13daa3c81f5fadc478aabe8477068ca

Will turn the release crank for a new point release soon.

**Comment by Windwoes** [comment]
Fixed in v1.6.1
