### ISSUE TITLE
CameraFactory does not work after updates

### ISSUE THREAD

**Issue by xboxman234** [OpenFTC/EasyOpenCV#72]
I am sorry if this is the wrong place or way to ask this but before updating my driver controller the webcamExample.java worked find and I was able to get pixels from a matrix but after the updates "import org.openftc.easyopencv.OpenCvCameraFactory" causes an error of cannot find symbol OpenCvCameraFactory or somthing along those lines and I am posting this here because it might be an update issue but if it is not and I am just dumb please point me in the right direciton thank you

**Comment by Windwoes** [comment]
This is a known bug in SDK v9.0 specific to OBJ, related to the fact that the EOCV artifact was compiled against a prior version of the SDK which still contained Vuforia. OBJ cries because it doesn't know how to handle that situation and thus excludes the CameraFactory class from the classpath.

Feel free to open an issue on the SDK repo for increased visibility to the community.

Note that this issue is specific to OBJ, it does not affect AS users.

**Comment by xboxman234** [comment]
Is there anything I can do? My team is relying on this code for detection because I havent been able to find any other way to get specific pixel values rgb.

**Comment by Windwoes** [comment]
You can either switch to using Android Studio, or port your EOCV pipeline to a Vision Processor to be used with the Vision Portal. The LearnJavaForFTC book has a chapter covering that.

**Comment by Windwoes** [comment]
(Also it will be fixed in the next SDK release but I don't have a timeline on that)

**Comment by xboxman234** [comment]
Sorry for the late question, if I switch to Android Studio can I just copy and paste my code or do I need to import more things?

**Comment by Windwoes** [comment]
You should be able to copy paste

**Comment by Windwoes** [comment]
This has been fixed in 2ac949f which will be included in the next release

**Comment by Windwoes** [comment]
Fixed in FTC SDK v9.1
